security.basic.enabled: false

token.secret: 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==

multipart.maxFileSize: 500Mb
multipart.maxRequestSize: 1024Mb